#设置语言
language: node_js
#设置语言版本
node_js: stable
#指定缓存模块
cache:
  directories:
    - node_modules
#指定分支
branches:
  only:
    - source
#安装前先配置一些属性
before_install:
  - git config user.name "51azxc"
  - git config user.email "hhj0862@outlook.com"
  - sed -i "s|github.com/51azxc/51azxc.github.io.git|${blog}@github.com/51azxc/51azxc.github.io.git" _config.yml
  - npm install -g hexo-cli
#安装依赖
install:
  - npm install
#执行清理及生成静态网页命令
script:
  - hexo clean
  - hexo generate
  - hexo deploy