name: DELPOY_HEXO_BLOG

on:
  push:
    branches: [ source ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: checkout
      uses: actions/checkout@v2
      with:
        submodules: true

   # - name: Update Submodule
   #   run: git submodule update --init --recursive

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.0
      with: 
        node-version: 12.x 
    
    - name: Setup Hexo
      env:
        HEXO_DEPLOY_KEY: ${{ secrets.DEPLOY_PRI_KEY }}        
      run: | 
        mkdir -p ~/.ssh/
        echo "$HEXO_DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git config --global user.name '51azxc'
        git config --global user.email 'hhj0862@outlook.com'
    
    - name: Install Dependency
      run: |
        npm install -g hexo-cli
        npm install
    
    - name: Build and Deploy
      run: |
        hexo clean
        hexo generate
        hexo deploy
